<?php
//Llamamos al autoloader
	require_once 'autoloader.php';
//Instanciamos el objeto
	$form = new Tarea();
//Llamamos al método show() para que rellene el formulario con los datos del id seleccionado
	$datos = $form->show();
 ?>

<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Borrar Tarea</title>
<link rel="stylesheet" type="text/css" href="form/view.css" media="all">
</head>
<body id="main_body">

	<img id="top" src="form/top.png" alt="">
	<div id="form_container">

		<h1><a>Borrar Tarea</a></h1>
<!-- Indicamos a donde deben enviarse los datos del formulario -->
		<form class="appnitro"  method="post" action="borrar.php">
					<div class="form_description">
			<h2>Borrar Tarea</h2>
			<p>¿Está seguro que desea borrar los siguientes datos?</p>
		</div>
			<ul >

					<li>
		<label class="description" for="title">Título </label>
<!-- Indicamos el dato que debe mostrarse en cada apartado del form a partir del objeto instanciado -->
		<div>
			<input name="title" class="element text medium" type="text" maxlength="255" value="<?=$datos["titulo"]?>"/>
		</div>
		</li>		<li>
		<label class="description" for="description">Descripción de la tarea </label>
		<div>
			<textarea name="description" class="element textarea medium"><?=$datos["descripcion"]?></textarea>
		</div>
		</li>		<li>
		<label class="description" for="dueDate">Fecha de vencimiento </label>
		<span>
			<input name="dueDate" class="element text" size="2" maxlength="2" value="<?=$datos["fecha_vencimiento"]?>" type="date">
		</span>
		</li>

		<li class="buttons">
		<!-- Indicamos el id de $_GET para que pueda ser recogido por $_POST -->
			    <input type="hidden" name="id" value="<?=$_GET["id"]?>" />
				<!-- Botón para borrar los datos que aparecen en el form -->
				<input class="button_text" type="submit" name="submit" value="Borrar Datos" />
				<!-- Botón para volver al listado de tareas -->
				<a href="lista.php"><input class="button_text" type="button" name="volver atras" value="Volver a lista"/></a>
		</li>
			</ul>
		</form>
		<div id="footer">
			Generated by <a href="http://www.floridauniversitaria.es">Florida</a>
		</div>
	</div>
	<img id="bottom" src="form/bottom.png" alt="">
	</body>
</html>
